<?php

namespace Container5KywV31;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_Zmo_AtService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.zmo._At' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.zmo._At'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'id' => ['privates', '.errored..service_locator.zmo._At.App\\Entity\\Formedeboxe', NULL, 'Cannot autowire service ".service_locator.zmo._At": it needs an instance of "App\\Entity\\Formedeboxe" but this type has been excluded in "config/services.yaml".'],
        ], [
            'id' => 'App\\Entity\\Formedeboxe',
        ]);
    }
}
