<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container5KywV31\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container5KywV31/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/Container5KywV31.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\Container5KywV31\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \Container5KywV31\App_KernelDevDebugContainer([
    'container.build_hash' => '5KywV31',
    'container.build_id' => 'eb55868b',
    'container.build_time' => 1706784137,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'Container5KywV31');
